void init_gpio(void);

enum ControllerInput {
	CONTROLLER_LEFT_LEFT   = 0x01,
	CONTROLLER_LEFT_UP     = 0x02,
	CONTROLLER_LEFT_RIGHT  = 0x04,
	CONTROLLER_LEFT_DOWN   = 0x08,

	CONTROLLER_RIGHT_LEFT  = 0x10,
	CONTROLLER_RIGHT_UP    = 0x20,
	CONTROLLER_RIGHT_RIGHT = 0x40,
	CONTROLLER_RIGHT_DOWN  = 0x80
};
